# 主题颜色方案：congo(默认绿)/ avocado / ocean / fire / slate / sandstone / sunrise
colorScheme = "slate"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
[footer]
  showScrollToTop = true
mainSections = ["posts"]
robots = "index, follow"

[homepage]
  layout = "card"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  groupByYear = false

[article]
  showDate = true
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = false
  sharingLinks = []

[list]
  showCards = true
  groupByYear = false
  cardView = true

[sitemap]
  excludedKinds = []
