colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
showScrollToTop = true

mainSections = ["posts"]
robots = "index, follow"

[homepage]
  layout = "card"
  homepageImage = ""
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = false
  sharingLinks = []

[list]
  showCards = true
  groupByYear = false
  cardView = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = false
  cardView = true
